"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    return queryInterface.bulkInsert("sc_charges_mappings", [
      {
        chargeNameFk: 1,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 2,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "3",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 3,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "3",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 4,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "3",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 5,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "3",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 6,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 7,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 8,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "2",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 9,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "2",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 10,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "3",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 11,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 12,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "2",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 13,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "2",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 14,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 15,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 16,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 17,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "2",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 18,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 19,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "2",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 20,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 21,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 22,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 23,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "2",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 24,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 25,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 26,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "2",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 27,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 28,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 29,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 30,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 31,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 32,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 33,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 34,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 35,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 36,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 37,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 38,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 39,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 40,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 41,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "3",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 42,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 43,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 44,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 45,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 46,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 47,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 48,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 49,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "2",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 50,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "2",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 51,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "2",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 52,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 53,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 54,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 55,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 56,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 57,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 58,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "3",
        chargeUOMFk: 3,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 59,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "3",
        chargeUOMFk: 3,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 60,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "3",
        chargeUOMFk: 3,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 61,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 62,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 63,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 64,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 65,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 66,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 67,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 68,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 69,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 70,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "2",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 71,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 72,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "2",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 73,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 74,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 75,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 76,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "2",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 77,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 78,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 79,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 80,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 81,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 82,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 83,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 84,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 85,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 86,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "2",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 87,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 88,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 89,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "2",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 90,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 91,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "3",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 92,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "2",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 93,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "3",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 94,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 95,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 96,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 97,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 98,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 99,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 100,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 101,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 102,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "2",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 103,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 104,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 105,
        chargeContainerIdFk: 0,
        chargeCategoryFk: "1",
        chargeUOMFk: 1,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 106,
        chargeContainerIdFk: 1,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 106,
        chargeContainerIdFk: 2,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 106,
        chargeContainerIdFk: 3,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 106,
        chargeContainerIdFk: 4,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 106,
        chargeContainerIdFk: 5,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 106,
        chargeContainerIdFk: 6,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 106,
        chargeContainerIdFk: 7,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 106,
        chargeContainerIdFk: 8,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 106,
        chargeContainerIdFk: 9,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 106,
        chargeContainerIdFk: 10,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 106,
        chargeContainerIdFk: 11,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 106,
        chargeContainerIdFk: 12,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 106,
        chargeContainerIdFk: 13,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 106,
        chargeContainerIdFk: 14,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 107,
        chargeContainerIdFk: 1,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 107,
        chargeContainerIdFk: 2,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 107,
        chargeContainerIdFk: 3,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 107,
        chargeContainerIdFk: 4,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 107,
        chargeContainerIdFk: 5,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 107,
        chargeContainerIdFk: 6,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 107,
        chargeContainerIdFk: 7,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 107,
        chargeContainerIdFk: 8,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 107,
        chargeContainerIdFk: 9,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 107,
        chargeContainerIdFk: 10,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 107,
        chargeContainerIdFk: 11,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 107,
        chargeContainerIdFk: 12,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 107,
        chargeContainerIdFk: 13,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 107,
        chargeContainerIdFk: 14,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 108,
        chargeContainerIdFk: 1,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 108,
        chargeContainerIdFk: 2,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 108,
        chargeContainerIdFk: 3,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 108,
        chargeContainerIdFk: 4,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 108,
        chargeContainerIdFk: 5,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 108,
        chargeContainerIdFk: 6,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 108,
        chargeContainerIdFk: 7,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 108,
        chargeContainerIdFk: 8,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 108,
        chargeContainerIdFk: 9,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 108,
        chargeContainerIdFk: 10,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 108,
        chargeContainerIdFk: 11,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 108,
        chargeContainerIdFk: 12,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 108,
        chargeContainerIdFk: 13,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 108,
        chargeContainerIdFk: 14,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 109,
        chargeContainerIdFk: 1,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 109,
        chargeContainerIdFk: 2,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 109,
        chargeContainerIdFk: 3,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 109,
        chargeContainerIdFk: 4,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 109,
        chargeContainerIdFk: 5,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 109,
        chargeContainerIdFk: 6,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 109,
        chargeContainerIdFk: 7,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 109,
        chargeContainerIdFk: 8,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 109,
        chargeContainerIdFk: 9,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 109,
        chargeContainerIdFk: 10,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 109,
        chargeContainerIdFk: 11,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 109,
        chargeContainerIdFk: 12,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 109,
        chargeContainerIdFk: 13,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 109,
        chargeContainerIdFk: 14,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 110,
        chargeContainerIdFk: 1,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 110,
        chargeContainerIdFk: 2,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 110,
        chargeContainerIdFk: 3,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 110,
        chargeContainerIdFk: 4,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 110,
        chargeContainerIdFk: 5,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 110,
        chargeContainerIdFk: 6,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 110,
        chargeContainerIdFk: 7,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 110,
        chargeContainerIdFk: 8,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 110,
        chargeContainerIdFk: 9,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 110,
        chargeContainerIdFk: 10,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 110,
        chargeContainerIdFk: 11,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 110,
        chargeContainerIdFk: 12,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 110,
        chargeContainerIdFk: 13,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 110,
        chargeContainerIdFk: 14,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 111,
        chargeContainerIdFk: 1,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 111,
        chargeContainerIdFk: 2,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 111,
        chargeContainerIdFk: 3,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 111,
        chargeContainerIdFk: 4,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 111,
        chargeContainerIdFk: 5,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 111,
        chargeContainerIdFk: 6,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 111,
        chargeContainerIdFk: 7,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 111,
        chargeContainerIdFk: 8,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 111,
        chargeContainerIdFk: 9,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 111,
        chargeContainerIdFk: 10,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 111,
        chargeContainerIdFk: 11,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 111,
        chargeContainerIdFk: 12,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 111,
        chargeContainerIdFk: 13,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 111,
        chargeContainerIdFk: 14,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 112,
        chargeContainerIdFk: 1,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 112,
        chargeContainerIdFk: 2,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 112,
        chargeContainerIdFk: 3,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 112,
        chargeContainerIdFk: 4,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 112,
        chargeContainerIdFk: 5,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 112,
        chargeContainerIdFk: 6,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 112,
        chargeContainerIdFk: 7,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 112,
        chargeContainerIdFk: 8,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 112,
        chargeContainerIdFk: 9,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 112,
        chargeContainerIdFk: 10,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 112,
        chargeContainerIdFk: 11,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 112,
        chargeContainerIdFk: 12,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 112,
        chargeContainerIdFk: 13,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 112,
        chargeContainerIdFk: 14,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 113,
        chargeContainerIdFk: 1,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 113,
        chargeContainerIdFk: 2,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 113,
        chargeContainerIdFk: 3,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 113,
        chargeContainerIdFk: 4,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 113,
        chargeContainerIdFk: 5,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 113,
        chargeContainerIdFk: 6,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 113,
        chargeContainerIdFk: 7,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 113,
        chargeContainerIdFk: 8,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 113,
        chargeContainerIdFk: 9,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 113,
        chargeContainerIdFk: 10,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 113,
        chargeContainerIdFk: 11,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 113,
        chargeContainerIdFk: 12,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 113,
        chargeContainerIdFk: 13,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        chargeNameFk: 113,
        chargeContainerIdFk: 14,
        chargeCategoryFk: "2",
        chargeUOMFk: 2,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    return queryInterface.bulkDelete("sc_charges_mappings", null, {});
  },
};
