"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert("sc_charges_segment_mappings", 
    [
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 2,
       chargeCodeId: 58,
       incoTermId: 1,
       movementTypeId: 2,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 2,
       chargeCodeId: 59,
       incoTermId: 1,
       movementTypeId: 2,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 93,
       incoTermId: 1,
       movementTypeId: 2,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 91,
       incoTermId: 1,
       movementTypeId: 2,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 85,
       incoTermId: 1,
       movementTypeId: 2,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 105,
       incoTermId: 1,
       movementTypeId: 2,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 500,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 45,
       incoTermId: 1,
       movementTypeId: 2,
       currencyId: 2,
       uomId: 1,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 2500,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 54,
       incoTermId: 1,
       movementTypeId: 2,
       currencyId: 2,
       uomId: 1,
       buyAmntPrUnit: 2000,
       minSellAmnt: 0,
       sellAmntPrUnit: 3000,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 88,
       incoTermId: 1,
       movementTypeId: 2,
       currencyId: 2,
       uomId: 1,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 2,
       chargeCodeId: 58,
       incoTermId: 4,
       movementTypeId: 3,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 2,
       chargeCodeId: 59,
       incoTermId: 4,
       movementTypeId: 3,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 93,
       incoTermId: 4,
       movementTypeId: 3,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 91,
       incoTermId: 4,
       movementTypeId: 3,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 105,
       incoTermId: 4,
       movementTypeId: 3,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 500,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 45,
       incoTermId: 4,
       movementTypeId: 3,
       currencyId: 2,
       uomId: 1,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 2500,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 88,
       incoTermId: 4,
       movementTypeId: 3,
       currencyId: 2,
       uomId: 1,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 2,
       chargeCodeId: 58,
       incoTermId: 2,
       movementTypeId: 3,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 2,
       chargeCodeId: 59,
       incoTermId: 2,
       movementTypeId: 3,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 93,
       incoTermId: 2,
       movementTypeId: 3,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 91,
       incoTermId: 2,
       movementTypeId: 3,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 105,
       incoTermId: 2,
       movementTypeId: 3,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 500,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 45,
       incoTermId: 2,
       movementTypeId: 3,
       currencyId: 2,
       uomId: 1,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 2500,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 54,
       incoTermId: 2,
       movementTypeId: 3,
       currencyId: 2,
       uomId: 1,
       buyAmntPrUnit: 2000,
       minSellAmnt: 0,
       sellAmntPrUnit: 3000,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 88,
       incoTermId: 2,
       movementTypeId: 3,
       currencyId: 2,
       uomId: 1,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 2,
       chargeCodeId: 58,
       incoTermId: 5,
       movementTypeId: 3,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 2,
       chargeCodeId: 59,
       incoTermId: 5,
       movementTypeId: 3,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 93,
       incoTermId: 5,
       movementTypeId: 3,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 91,
       incoTermId: 5,
       movementTypeId: 3,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 105,
       incoTermId: 5,
       movementTypeId: 3,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 500,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 45,
       incoTermId: 5,
       movementTypeId: 3,
       currencyId: 2,
       uomId: 1,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 2500,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 54,
       incoTermId: 5,
       movementTypeId: 3,
       currencyId: 2,
       uomId: 1,
       buyAmntPrUnit: 2000,
       minSellAmnt: 0,
       sellAmntPrUnit: 3000,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 2,
       chargeCodeId: 58,
       incoTermId: 5,
       movementTypeId: 2,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 2,
       chargeCodeId: 59,
       incoTermId: 5,
       movementTypeId: 2,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 93,
       incoTermId: 5,
       movementTypeId: 2,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 91,
       incoTermId: 5,
       movementTypeId: 2,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 85,
       incoTermId: 5,
       movementTypeId: 2,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 105,
       incoTermId: 5,
       movementTypeId: 2,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 500,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 45,
       incoTermId: 5,
       movementTypeId: 2,
       currencyId: 2,
       uomId: 1,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 2500,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 54,
       incoTermId: 5,
       movementTypeId: 2,
       currencyId: 2,
       uomId: 1,
       buyAmntPrUnit: 2000,
       minSellAmnt: 0,
       sellAmntPrUnit: 3000,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 88,
       incoTermId: 5,
       movementTypeId: 2,
       currencyId: 2,
       uomId: 1,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 2,
       chargeCodeId: 58,
       incoTermId: 6,
       movementTypeId: 3,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 2,
       chargeCodeId: 59,
       incoTermId: 6,
       movementTypeId: 3,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 93,
       incoTermId: 6,
       movementTypeId: 3,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 91,
       incoTermId: 6,
       movementTypeId: 3,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 105,
       incoTermId: 6,
       movementTypeId: 3,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 500,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 45,
       incoTermId: 6,
       movementTypeId: 3,
       currencyId: 2,
       uomId: 1,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 2500,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 54,
       incoTermId: 6,
       movementTypeId: 3,
       currencyId: 2,
       uomId: 1,
       buyAmntPrUnit: 2000,
       minSellAmnt: 0,
       sellAmntPrUnit: 3000,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 2,
       chargeCodeId: 58,
       incoTermId: 6,
       movementTypeId: 2,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 2,
       chargeCodeId: 59,
       incoTermId: 6,
       movementTypeId: 2,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 93,
       incoTermId: 6,
       movementTypeId: 2,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 91,
       incoTermId: 6,
       movementTypeId: 2,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 85,
       incoTermId: 6,
       movementTypeId: 2,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 105,
       incoTermId: 6,
       movementTypeId: 2,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 500,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 45,
       incoTermId: 6,
       movementTypeId: 2,
       currencyId: 2,
       uomId: 1,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 2500,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 54,
       incoTermId: 6,
       movementTypeId: 2,
       currencyId: 2,
       uomId: 1,
       buyAmntPrUnit: 2000,
       minSellAmnt: 0,
       sellAmntPrUnit: 3000,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 88,
       incoTermId: 6,
       movementTypeId: 2,
       currencyId: 2,
       uomId: 1,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 2,
       chargeCodeId: 58,
       incoTermId: 10,
       movementTypeId: 4,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 2,
       chargeCodeId: 59,
       incoTermId: 10,
       movementTypeId: 4,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 93,
       incoTermId: 10,
       movementTypeId: 4,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 91,
       incoTermId: 10,
       movementTypeId: 4,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 105,
       incoTermId: 10,
       movementTypeId: 4,
       currencyId: 1,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 500,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 45,
       incoTermId: 10,
       movementTypeId: 4,
       currencyId: 1,
       uomId: 1,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 2500,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 114,
       incoTermId: 10,
       movementTypeId: 4,
       currencyId: 1,
       uomId: 1,
       buyAmntPrUnit: 2000,
       minSellAmnt: 0,
       sellAmntPrUnit: 3000,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 36,
       incoTermId: 10,
       movementTypeId: 4,
       currencyId: 1,
       uomId: 1,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 3,
       incoTermId: 10,
       movementTypeId: 4,
       currencyId: 1,
       uomId: 1,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 39,
       incoTermId: 10,
       movementTypeId: 4,
       currencyId: 1,
       uomId: 1,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 35,
       incoTermId: 10,
       movementTypeId: 4,
       currencyId: 1,
       uomId: 1,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 114,
       incoTermId: 10,
       movementTypeId: 4,
       currencyId: 1,
       uomId: 1,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 2,
       chargeCodeId: 58,
       incoTermId: 10,
       movementTypeId: 1,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 2,
       chargeCodeId: 59,
       incoTermId: 10,
       movementTypeId: 1,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 93,
       incoTermId: 10,
       movementTypeId: 1,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 91,
       incoTermId: 10,
       movementTypeId: 1,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 85,
       incoTermId: 1,
       movementTypeId: 1,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 15,
       minSellAmnt: 250,
       sellAmntPrUnit: 25,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 105,
       incoTermId: 1,
       movementTypeId: 1,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 25,
       minSellAmnt: 300,
       sellAmntPrUnit: 30,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 45,
       incoTermId: 1,
       movementTypeId: 1,
       currencyId: 2,
       uomId: 1,
       buyAmntPrUnit: 2000,
       minSellAmnt: 2500,
       sellAmntPrUnit: 2500,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 54,
       incoTermId: 1,
       movementTypeId: 1,
       currencyId: 2,
       uomId: 1,
       buyAmntPrUnit: 2000,
       minSellAmnt: 3000,
       sellAmntPrUnit: 3000,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 105,
       incoTermId: 10,
       movementTypeId: 1,
       currencyId: 1,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 500,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 45,
       incoTermId: 10,
       movementTypeId: 1,
       currencyId: 1,
       uomId: 1,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 2500,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 114,
       incoTermId: 10,
       movementTypeId: 1,
       currencyId: 1,
       uomId: 1,
       buyAmntPrUnit: 2000,
       minSellAmnt: 0,
       sellAmntPrUnit: 3000,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 36,
       incoTermId: 10,
       movementTypeId: 1,
       currencyId: 1,
       uomId: 1,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 3,
       incoTermId: 10,
       movementTypeId: 1,
       currencyId: 1,
       uomId: 1,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 39,
       incoTermId: 10,
       movementTypeId: 1,
       currencyId: 1,
       uomId: 1,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 35,
       incoTermId: 10,
       movementTypeId: 1,
       currencyId: 1,
       uomId: 1,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 114,
       incoTermId: 10,
       movementTypeId: 1,
       currencyId: 1,
       uomId: 1,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 2,
       chargeCodeId: 58,
       incoTermId: 11,
       movementTypeId: 4,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 2,
       chargeCodeId: 59,
       incoTermId: 11,
       movementTypeId: 4,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 93,
       incoTermId: 11,
       movementTypeId: 4,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 91,
       incoTermId: 11,
       movementTypeId: 4,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 105,
       incoTermId: 11,
       movementTypeId: 4,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 500,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 45,
       incoTermId: 11,
       movementTypeId: 4,
       currencyId: 2,
       uomId: 1,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 2500,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 54,
       incoTermId: 11,
       movementTypeId: 4,
       currencyId: 2,
       uomId: 1,
       buyAmntPrUnit: 2000,
       minSellAmnt: 0,
       sellAmntPrUnit: 3000,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 36,
       incoTermId: 11,
       movementTypeId: 4,
       currencyId: 1,
       uomId: 1,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 3,
       incoTermId: 11,
       movementTypeId: 4,
       currencyId: 1,
       uomId: 1,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 39,
       incoTermId: 11,
       movementTypeId: 4,
       currencyId: 1,
       uomId: 1,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 35,
       incoTermId: 11,
       movementTypeId: 4,
       currencyId: 1,
       uomId: 1,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 2,
       chargeCodeId: 58,
       incoTermId: 11,
       movementTypeId: 1,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 2,
       chargeCodeId: 59,
       incoTermId: 11,
       movementTypeId: 1,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 93,
       incoTermId: 11,
       movementTypeId: 1,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 91,
       incoTermId: 11,
       movementTypeId: 1,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 85,
       incoTermId: 11,
       movementTypeId: 1,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 105,
       incoTermId: 11,
       movementTypeId: 1,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 500,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 45,
       incoTermId: 11,
       movementTypeId: 1,
       currencyId: 2,
       uomId: 1,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 2500,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 54,
       incoTermId: 11,
       movementTypeId: 1,
       currencyId: 2,
       uomId: 1,
       buyAmntPrUnit: 2000,
       minSellAmnt: 0,
       sellAmntPrUnit: 3000,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 105,
       incoTermId: 11,
       movementTypeId: 1,
       currencyId: 2,
       uomId: 3,
       buyAmntPrUnit: 0,
       minSellAmnt: 500,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 45,
       incoTermId: 11,
       movementTypeId: 1,
       currencyId: 2,
       uomId: 1,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 2500,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 54,
       incoTermId: 11,
       movementTypeId: 1,
       currencyId: 2,
       uomId: 1,
       buyAmntPrUnit: 2000,
       minSellAmnt: 0,
       sellAmntPrUnit: 3000,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 36,
       incoTermId: 11,
       movementTypeId: 1,
       currencyId: 1,
       uomId: 1,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 3,
       incoTermId: 11,
       movementTypeId: 1,
       currencyId: 1,
       uomId: 1,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 39,
       incoTermId: 11,
       movementTypeId: 1,
       currencyId: 1,
       uomId: 1,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 0,
       cargoTypeId: 7,
       chargeTypeId: 1,
       chargeCodeId: 35,
       incoTermId: 11,
       movementTypeId: 1,
       currencyId: 1,
       uomId: 1,
       buyAmntPrUnit: 0,
       minSellAmnt: 0,
       sellAmntPrUnit: 0,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 157,
       cargoTypeId: 1,
       chargeTypeId: 1,
       chargeCodeId: 54,
       incoTermId: 1,
       movementTypeId: 1,
       currencyId: 2,
       uomId: 1,
       buyAmntPrUnit: 2500,
       minSellAmnt: 2700,
       sellAmntPrUnit: 2780,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 157,
       cargoTypeId: 1,
       chargeTypeId: 1,
       chargeCodeId: 94,
       incoTermId: 1,
       movementTypeId: 1,
       currencyId: 2,
       uomId: 1,
       buyAmntPrUnit: 25,
       minSellAmnt: 30,
       sellAmntPrUnit: 35,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      },
      {
       segmentId: 5,
       airLineId: 29,
       cargoTypeId: 1,
       chargeTypeId: 1,
       chargeCodeId: 63,
       incoTermId: 1,
       movementTypeId: 1,
       currencyId: 2,
       uomId: 1,
       buyAmntPrUnit: 25,
       minSellAmnt: 30,
       sellAmntPrUnit: 30,
       validTill: "2024-12-31",
       status: true,
       globalCompanyId: 2,
       branchCountryId: 1,
       branchNameId: 1,
       createdBy: 4,
       modifiedBy: 4,
       createdAt: new Date(),
       updatedAt: new Date()
      }
     ]);
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('sc_charges_segment_mappings', null, {});
  },
};
