'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up (queryInterface, Sequelize) {
    return queryInterface.bulkInsert('sc_airline_schedules', 
    [
      {
        cargoTypeId: 1,
        afPOLId: 5681,
        afPODId: 9,
        route: "DIRECT",
        directTransitPortId: 9,
        transitTime: 1,
        airLineCarrierId: 275,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 5681,
        afPODId: 5657,
        route: "DIRECT",
        directTransitPortId: 5657,
        transitTime: 2,
        airLineCarrierId: 275,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 5681,
        afPODId: 5,
        route: "DIRECT",
        directTransitPortId: 5,
        transitTime: 2,
        airLineCarrierId: 29,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 5681,
        afPODId: 4720,
        route: "DIRECT",
        directTransitPortId: 4720,
        transitTime: 2,
        airLineCarrierId: 275,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 5681,
        afPODId: 7,
        route: "DIRECT",
        directTransitPortId: 7,
        transitTime: 2,
        airLineCarrierId: 29,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 5681,
        afPODId: 311,
        route: "DIRECT",
        directTransitPortId: 311,
        transitTime: 2,
        airLineCarrierId: 275,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 3018,
        afPODId: 9,
        route: "DIRECT",
        directTransitPortId: 9,
        transitTime: 2,
        airLineCarrierId: 275,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 3018,
        afPODId: 5657,
        route: "DIRECT",
        directTransitPortId: 5657,
        transitTime: 2,
        airLineCarrierId: 275,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 3018,
        afPODId: 5,
        route: "DIRECT",
        directTransitPortId: 5,
        transitTime: 2,
        airLineCarrierId: 29,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 3018,
        afPODId: 4720,
        route: "DIRECT",
        directTransitPortId: 4720,
        transitTime: 2,
        airLineCarrierId: 275,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 3018,
        afPODId: 7,
        route: "DIRECT",
        directTransitPortId: 7,
        transitTime: 2,
        airLineCarrierId: 29,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 3018,
        afPODId: 311,
        route: "DIRECT",
        directTransitPortId: 311,
        transitTime: 2,
        airLineCarrierId: 275,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 847,
        afPODId: 9,
        route: "DIRECT",
        directTransitPortId: 9,
        transitTime: 2,
        airLineCarrierId: 275,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 847,
        afPODId: 5657,
        route: "DIRECT",
        directTransitPortId: 5657,
        transitTime: 2,
        airLineCarrierId: 275,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 847,
        afPODId: 5,
        route: "DIRECT",
        directTransitPortId: 5,
        transitTime: 2,
        airLineCarrierId: 29,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 847,
        afPODId: 7,
        route: "DIRECT",
        directTransitPortId: 7,
        transitTime: 2,
        airLineCarrierId: 29,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 847,
        afPODId: 4720,
        route: "DIRECT",
        directTransitPortId: 4720,
        transitTime: 2,
        airLineCarrierId: 275,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 847,
        afPODId: 311,
        route: "DIRECT",
        directTransitPortId: 311,
        transitTime: 2,
        airLineCarrierId: 275,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 2040,
        afPODId: 9,
        route: "DIRECT",
        directTransitPortId: 9,
        transitTime: 2,
        airLineCarrierId: 275,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 2040,
        afPODId: 5657,
        route: "DIRECT",
        directTransitPortId: 5657,
        transitTime: 2,
        airLineCarrierId: 275,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 2040,
        afPODId: 5,
        route: "DIRECT",
        directTransitPortId: 5,
        transitTime: 2,
        airLineCarrierId: 29,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 2040,
        afPODId: 7,
        route: "DIRECT",
        directTransitPortId: 7,
        transitTime: 2,
        airLineCarrierId: 29,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 2040,
        afPODId: 4720,
        route: "DIRECT",
        directTransitPortId: 4720,
        transitTime: 2,
        airLineCarrierId: 275,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 2040,
        afPODId: 311,
        route: "DIRECT",
        directTransitPortId: 311,
        transitTime: 2,
        airLineCarrierId: 275,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 3427,
        afPODId: 9,
        route: "DIRECT",
        directTransitPortId: 0,
        transitTime: 1,
        airLineCarrierId: 275,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 3427,
        afPODId: 5657,
        route: "DIRECT",
        directTransitPortId: 5657,
        transitTime: 2,
        airLineCarrierId: 275,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 3427,
        afPODId: 5,
        route: "DIRECT",
        directTransitPortId: 5,
        transitTime: 2,
        airLineCarrierId: 29,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 3427,
        afPODId: 9,
        route: "TRANSIT",
        directTransitPortId: 86,
        transitTime: 3,
        airLineCarrierId: 191,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 3427,
        afPODId: 5657,
        route: "TRANSIT",
        directTransitPortId: 5657,
        transitTime: 3,
        airLineCarrierId: 191,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 3427,
        afPODId: 5,
        route: "TRANSIT",
        directTransitPortId: 85,
        transitTime: 3,
        airLineCarrierId: 191,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 3427,
        afPODId: 9,
        route: "TRANSIT",
        directTransitPortId: 4720,
        transitTime: 3,
        airLineCarrierId: 227,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 3427,
        afPODId: 4720,
        route: "DIRECT",
        directTransitPortId: 4720,
        transitTime: 2,
        airLineCarrierId: 275,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 3427,
        afPODId: 7,
        route: "DIRECT",
        directTransitPortId: 7,
        transitTime: 2,
        airLineCarrierId: 29,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 3427,
        afPODId: 4720,
        route: "TRANSIT",
        directTransitPortId: 4720,
        transitTime: 3,
        airLineCarrierId: 191,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 3427,
        afPODId: 7,
        route: "TRANSIT",
        directTransitPortId: 7,
        transitTime: 3,
        airLineCarrierId: 191,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 3427,
        afPODId: 311,
        route: "TRANSIT",
        directTransitPortId: 311,
        transitTime: 3,
        airLineCarrierId: 191,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 6280,
        afPODId: 9,
        route: "DIRECT",
        directTransitPortId: 0,
        transitTime: 2,
        airLineCarrierId: 275,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 6280,
        afPODId: 5657,
        route: "DIRECT",
        directTransitPortId: 5657,
        transitTime: 2,
        airLineCarrierId: 275,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 6280,
        afPODId: 5,
        route: "DIRECT",
        directTransitPortId: 5,
        transitTime: 2,
        airLineCarrierId: 29,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 6280,
        afPODId: 4720,
        route: "DIRECT",
        directTransitPortId: 4720,
        transitTime: 2,
        airLineCarrierId: 275,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 6280,
        afPODId: 7,
        route: "DIRECT",
        directTransitPortId: 7,
        transitTime: 2,
        airLineCarrierId: 29,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 6280,
        afPODId: 311,
        route: "DIRECT",
        directTransitPortId: 311,
        transitTime: 2,
        airLineCarrierId: 275,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 2609,
        afPODId: 9,
        route: "DIRECT",
        directTransitPortId: 0,
        transitTime: 2,
        airLineCarrierId: 275,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 2609,
        afPODId: 5657,
        route: "DIRECT",
        directTransitPortId: 5657,
        transitTime: 2,
        airLineCarrierId: 275,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 2609,
        afPODId: 5,
        route: "DIRECT",
        directTransitPortId: 5,
        transitTime: 2,
        airLineCarrierId: 29,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 2609,
        afPODId: 4720,
        route: "DIRECT",
        directTransitPortId: 4720,
        transitTime: 2,
        airLineCarrierId: 275,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 2609,
        afPODId: 7,
        route: "DIRECT",
        directTransitPortId: 7,
        transitTime: 2,
        airLineCarrierId: 29,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 2609,
        afPODId: 311,
        route: "DIRECT",
        directTransitPortId: 311,
        transitTime: 2,
        airLineCarrierId: 275,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 3544,
        afPODId: 9,
        route: "DIRECT",
        directTransitPortId: 0,
        transitTime: 1,
        airLineCarrierId: 275,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 3544,
        afPODId: 5657,
        route: "DIRECT",
        directTransitPortId: 5657,
        transitTime: 2,
        airLineCarrierId: 275,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 3544,
        afPODId: 5,
        route: "DIRECT",
        directTransitPortId: 5,
        transitTime: 2,
        airLineCarrierId: 29,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 3544,
        afPODId: 4720,
        route: "DIRECT",
        directTransitPortId: 4720,
        transitTime: 2,
        airLineCarrierId: 275,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 3544,
        afPODId: 7,
        route: "DIRECT",
        directTransitPortId: 7,
        transitTime: 2,
        airLineCarrierId: 29,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 3544,
        afPODId: 311,
        route: "DIRECT",
        directTransitPortId: 311,
        transitTime: 2,
        airLineCarrierId: 275,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 3136,
        afPODId: 9,
        route: "DIRECT",
        directTransitPortId: 0,
        transitTime: 2,
        airLineCarrierId: 275,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 3136,
        afPODId: 5657,
        route: "DIRECT",
        directTransitPortId: 5657,
        transitTime: 2,
        airLineCarrierId: 275,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 3136,
        afPODId: 5,
        route: "DIRECT",
        directTransitPortId: 5,
        transitTime: 2,
        airLineCarrierId: 29,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 3136,
        afPODId: 4720,
        route: "DIRECT",
        directTransitPortId: 4720,
        transitTime: 2,
        airLineCarrierId: 275,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 3136,
        afPODId: 7,
        route: "DIRECT",
        directTransitPortId: 7,
        transitTime: 2,
        airLineCarrierId: 29,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        cargoTypeId: 1,
        afPOLId: 3136,
        afPODId: 311,
        route: "DIRECT",
        directTransitPortId: 311,
        transitTime: 2,
        airLineCarrierId: 275,
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt : new Date(),
        updatedAt : new Date()
      }
    ]
    )
  },

  async down (queryInterface, Sequelize) {
    return queryInterface.bulkDelete('sc_airline_schedules', null, {});
  }
};
