"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    return queryInterface.bulkInsert(
      "sc_bank_infos",
      [
        {
          bankCustomerIdFk: 7,
          bankCustomerDetailsIdFk: 6,
          bankCode: "MNH",
          bankBranch: "Manhattan",
          bankName: "IDFC",
          bankAddress: null,
          bankAccNameCheque: null,
          bankAccNameFull: null,
          bankAccNumber: 1234564,
          bankAccType: null,
          bankCurrency: null,
          bankSwiftCode: null,
          bankIfscCode: null,
          bankIbanCode: null,
          bankControlDigitCode: null,
          bankStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bankCustomerIdFk: 3,
          bankCustomerDetailsIdFk: 2,
          bankCode: "IDB",
          bankBranch: "Pallavaram",
          bankName: "IOB",
          bankAddress: null,
          bankAccNameCheque: "ABDUL HANNAN",
          bankAccNameFull: "Abdul Hannan",
          bankAccNumber: 1234564,
          bankAccType: "Savings",
          bankCurrency: null,
          bankSwiftCode: null,
          bankIfscCode: null,
          bankIbanCode: null,
          bankControlDigitCode: null,
          bankStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bankCustomerIdFk: 3,
          bankCustomerDetailsIdFk: 2,
          bankCode: "Pytm",
          bankBranch: "Noida",
          bankName: "Paytm",
          bankAddress: null,
          bankAccNameCheque: null,
          bankAccNameFull: "Yasmeen",
          bankAccNumber: 1234564,
          bankAccType: "Savings",
          bankCurrency: null,
          bankSwiftCode: null,
          bankIfscCode: null,
          bankIbanCode: null,
          bankControlDigitCode: null,
          bankStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bankCustomerIdFk: 9,
          bankCustomerDetailsIdFk: 8,
          bankCode: "SD",
          bankBranch: "ASD",
          bankName: "ASD",
          bankAddress: null,
          bankAccNameCheque: null,
          bankAccNameFull: null,
          bankAccNumber: null,
          bankAccType: null,
          bankCurrency: null,
          bankSwiftCode: null,
          bankIfscCode: null,
          bankIbanCode: null,
          bankControlDigitCode: null,
          bankStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bankCustomerIdFk: 10,
          bankCustomerDetailsIdFk: 9,
          bankCode: "ABCD",
          bankBranch: "IDB",
          bankName: "ABCD",
          bankAddress: null,
          bankAccNameCheque: "ABDUL",
          bankAccNameFull: "ABDUL HANNAN",
          bankAccNumber: null,
          bankAccType: null,
          bankCurrency: null,
          bankSwiftCode: null,
          bankIfscCode: null,
          bankIbanCode: null,
          bankControlDigitCode: null,
          bankStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bankCustomerIdFk: 13,
          bankCustomerDetailsIdFk: 12,
          bankCode: "sd",
          bankBranch: "sda",
          bankName: "asd",
          bankAddress: null,
          bankAccNameCheque: null,
          bankAccNameFull: null,
          bankAccNumber: null,
          bankAccType: null,
          bankCurrency: null,
          bankSwiftCode: null,
          bankIfscCode: null,
          bankIbanCode: null,
          bankControlDigitCode: null,
          bankStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ]
    );
  },

  async down(queryInterface, Sequelize) {
    return queryInterface.bulkDelete("sc_bank_infos", null, {});
  },
};
