"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    return queryInterface.bulkInsert("sc_customers", [
      {
		id : 1,
		customerBranchId : 1,
		customerName : "DEIF AS",
		customerCode : "DKDE0001",
		customerCountryIdFk : 59,
		customerStatus : true,
    // custGlobalCompanyId: 2,
    // custCompanyCountryId: 1,
    // custCompanyBranchId :1,
		createdBy : 4,
		modifiedBy : 4,
		createdAt : new Date(),
		updatedAt : new Date(),
	},
	{
		id : 2,
		customerBranchId : 1,
		customerName : "TIMESCAN LOGISTICS INDIA PRIVATE LIMITED",
		customerCode : "INTI0001",
		customerCountryIdFk : 105,
		customerStatus : true,
    // custGlobalCompanyId: 2,
    // custCompanyCountryId: 1,
    // custCompanyBranchId :1,
		createdBy : 4,
		modifiedBy : 4,
		createdAt : new Date(),
		updatedAt : new Date(),
	},
	{
		id : 3,
		customerBranchId : 1,
		customerName : "SHORELINE EXPRESS, INC",
		customerCode : "USSH0001",
		customerCountryIdFk : 233,
		customerStatus : true,
    // custGlobalCompanyId: 2,
    // custCompanyCountryId: 1,
    // custCompanyBranchId :1,
		createdBy : 4,
		modifiedBy : 4,
		createdAt : new Date(),
		updatedAt : new Date(),
	},
	{
		id : 4,
		customerBranchId : 1,
		customerName : "CN LOGISTICS INTERNATIONAL HOLDINGS LIMITED",
		customerCode : "HKCN0001",
		customerCountryIdFk : 95,
		customerStatus : true,
    // custGlobalCompanyId: 2,
    // custCompanyCountryId: 1,
    // custCompanyBranchId :1,
		createdBy : 4,
		modifiedBy : 4,
		createdAt : new Date(),
		updatedAt : new Date(),
	},
	{
		id : 5,
		customerBranchId : 1,
		customerName : "EXPRESS AIR FREIGHT (HK) LTD.",
		customerCode : "HKEX0002",
		customerCountryIdFk : 74,
		customerStatus : true,
    // custGlobalCompanyId: 2,
    // custCompanyCountryId: 1,
    // custCompanyBranchId :1,
		createdBy : 4,
		modifiedBy : 4,
		createdAt : new Date(),
		updatedAt : new Date(),
	},
	{
		id : 6,
		customerBranchId : 1,
		customerName : "EXPRESS AIR FREIGHT (HK) ",
		customerCode : "USA&0002",
		customerCountryIdFk : 95,
		customerStatus : true,
    // custGlobalCompanyId: 2,
    // custCompanyCountryId: 1,
    // custCompanyBranchId :1,
		createdBy : 4,
		modifiedBy : 4,
		createdAt : new Date(),
		updatedAt : new Date(),
	},
	{
		id : 7,
		customerBranchId : 1,
		customerName : "B2B TRANSPORT",
		customerCode : "USB20003",
		customerCountryIdFk : 233,
		customerStatus : true,
    // custGlobalCompanyId: 2,
    // custCompanyCountryId: 1,
    // custCompanyBranchId :1,
		createdBy : 4,
		modifiedBy : 4,
		createdAt : new Date(),
		updatedAt : new Date(),
	},
	{
		id : 8,
		customerBranchId : 1,
		customerName : "AMERITRANS FREIGHT INTERNATIONAL",
		customerCode : "USAM0004",
		customerCountryIdFk : 233,
		customerStatus : true,
    // custGlobalCompanyId: 2,
    // custCompanyCountryId: 1,
    // custCompanyBranchId :1,
		createdBy : 4,
		modifiedBy : 4,
		createdAt : new Date(),
		updatedAt : new Date(),
	},
	{
		id : 9,
		customerBranchId : 1,
		customerName : "SEABORNE INTERNATIONAL, INC",
		customerCode : "USSE0005",
		customerCountryIdFk : 233,
		customerStatus : true,
    // custGlobalCompanyId: 2,
    // custCompanyCountryId: 1,
    // custCompanyBranchId :1,
		createdBy : 4,
		modifiedBy : 4,
		createdAt : new Date(),
		updatedAt : new Date(),
	},
	{
		id : 10,
		customerBranchId : 1,
		customerName : "PBV SHIPPING USA INC.",
		customerCode : "USPB0006",
		customerCountryIdFk : 233,
		customerStatus : true,
    // custGlobalCompanyId: 2,
    // custCompanyCountryId: 1,
    // custCompanyBranchId :1,
		createdBy : 4,
		modifiedBy : 4,
		createdAt : new Date(),
		updatedAt : new Date(),
	},
	{
		id : 11,
		customerBranchId : 1,
		customerName : "MARS SHIPPING SERVICES",
		customerCode : "BHMA0001",
		customerCountryIdFk : 23,
		customerStatus : false,
    // custGlobalCompanyId: 2,
    // custCompanyCountryId: 1,
    // custCompanyBranchId :1,
		createdBy : 4,
		modifiedBy : 4,
		createdAt : new Date(),
		updatedAt : new Date(),
	},
	{
		id : 12,
		customerBranchId : 1,
		customerName : "MARS SHIPPING SERVICES",
		customerCode : "SAMA0001",
		customerCountryIdFk : 193,
		customerStatus : true,
    // custGlobalCompanyId: 2,
    // custCompanyCountryId: 1,
    // custCompanyBranchId :1,
		createdBy : 4,
		modifiedBy : 4,
		createdAt : new Date(),
		updatedAt : new Date(),
	},
	{
		id : 13,
		customerBranchId : 1,
		customerName : "LINK INDIA LOGISTICS",
		customerCode : "INLI0002",
		customerCountryIdFk : 105,
		customerStatus : true,
    // custGlobalCompanyId: 2,
    // custCompanyCountryId: 1,
    // custCompanyBranchId :1,
		createdBy : 4,
		modifiedBy : 4,
		createdAt : new Date(),
		updatedAt : new Date(),
	},
	{
		id : 14,
		customerBranchId : 1,
		customerName : "MARS SHIPPING SERVICES",
		customerCode : "INMA0003",
		customerCountryIdFk : 105,
		customerStatus : true,
    // custGlobalCompanyId: 2,
    // custCompanyCountryId: 1,
    // custCompanyBranchId :1,
		createdBy : 4,
		modifiedBy : 4,
		createdAt : new Date(),
		updatedAt : new Date(),
	},
	{
		id : 15,
		customerBranchId : 1,
		customerName : "CARGOMAR SHIPPING AND LOGISTICS",
		customerCode : "INCA0004",
		customerCountryIdFk : 105,
		customerStatus : true,
    // custGlobalCompanyId: 2,
    // custCompanyCountryId: 1,
    // custCompanyBranchId :1,
		createdBy : 4,
		modifiedBy : 4,
		createdAt : new Date(),
		updatedAt : new Date(),
	},
	{
		id : 16,
		customerBranchId : 1,
		customerName : "NEXUS FREIGHT",
		customerCode : "INNE0005",
		customerCountryIdFk : 105,
		customerStatus : true,
    // custGlobalCompanyId: 2,
    // custCompanyCountryId: 1,
    // custCompanyBranchId :1,
		createdBy : 4,
		modifiedBy : 4,
		createdAt : new Date(),
		updatedAt : new Date(),
	},
	{
		id : 17,
		customerBranchId : 1,
		customerName : "SEAFREIGHT SHIPPING AGENCY",
		customerCode : "INSE0006",
		customerCountryIdFk : 105,
		customerStatus : true,
    // custGlobalCompanyId: 2,
    // custCompanyCountryId: 1,
    // custCompanyBranchId :1,
		createdBy : 4,
		modifiedBy : 4,
		createdAt : new Date(),
		updatedAt : new Date(),
	},
	{
		id : 18,
		customerBranchId : 1,
		customerName : "EXPEDITORS INTERNATIONAL INDIA PRIVATE LTD",
		customerCode : "INEX0007",
		customerCountryIdFk : 105,
		customerStatus : true,
    // custGlobalCompanyId: 2,
    // custCompanyCountryId: 1,
    // custCompanyBranchId :1,
		createdBy : 4,
		modifiedBy : 4,
		createdAt : new Date(),
		updatedAt : new Date(),
	},
	{
		id : 19,
		customerBranchId : 1,
		customerName : "TEAM GLOBAL LOGISTICS PVT LTD",
		customerCode : "INTE0008",
		customerCountryIdFk : 105,
		customerStatus : true,
    // custGlobalCompanyId: 2,
    // custCompanyCountryId: 1,
    // custCompanyBranchId :1,
		createdBy : 4,
		modifiedBy : 4,
		createdAt : new Date(),
		updatedAt : new Date(),
	},
	{
		id : 20,
		customerBranchId : 1,
		customerName : "ALLCARGO LOGISTICS LTD",
		customerCode : "INAL0009",
		customerCountryIdFk : 105,
		customerStatus : true,
    // custGlobalCompanyId: 2,
    // custCompanyCountryId: 1,
    // custCompanyBranchId :1,
		createdBy : 4,
		modifiedBy : 4,
		createdAt : new Date(),
		updatedAt : new Date(),
	},
	{
		id : 21,
		customerBranchId : 1,
		customerName : "YUSEN LOGISTICS (INDIA) PRIVATE LIMITED",
		customerCode : "INYU0010",
		customerCountryIdFk : 105,
		customerStatus : true,
    // custGlobalCompanyId: 2,
    // custCompanyCountryId: 1,
    // custCompanyBranchId :1,
		createdBy : 4,
		modifiedBy : 4,
		createdAt : new Date(),
		updatedAt : new Date(),
	},
	{
		id : 22,
		customerBranchId : 1,
		customerName : "SMART SHIPPING SERVICESS",
		customerCode : "INSM0011",
		customerCountryIdFk : 105,
		customerStatus : true,
    // custGlobalCompanyId: 2,
    // custCompanyCountryId: 1,
    // custCompanyBranchId :1,
		createdBy : 4,
		modifiedBy : 4,
		createdAt : new Date(),
		updatedAt : new Date(),
	},
	{
		id : 23,
		customerBranchId : 1,
		customerName : "MI EXPORTS",
		customerCode : "INMI0012",
		customerCountryIdFk : 105,
		customerStatus : true,
    // custGlobalCompanyId: 2,
    // custCompanyCountryId: 1,
    // custCompanyBranchId :1,
		createdBy : 4,
		modifiedBy : 4,
		createdAt : new Date(),
		updatedAt : new Date(),
	},
	{
		id : 24,
		customerBranchId : 1,
		customerName : "GG EXPORTS",
		customerCode : "INGG0013",
		customerCountryIdFk : 105,
		customerStatus : true,
    // custGlobalCompanyId: 2,
    // custCompanyCountryId: 1,
    // custCompanyBranchId :1,
		createdBy : 4,
		modifiedBy : 4,
		createdAt : new Date(),
		updatedAt : new Date(),
	},
	{
		id : 25,
		customerBranchId : 1,
		customerName : "MABARA MANUFACTURING COMPANY",
		customerCode : "INMA0014",
		customerCountryIdFk : 105,
		customerStatus : true,
    // custGlobalCompanyId: 2,
    // custCompanyCountryId: 1,
    // custCompanyBranchId :1,
		createdBy : 4,
		modifiedBy : 4,
		createdAt : new Date(),
		updatedAt : new Date(),
	},
	{
		id : 26,
		customerBranchId : 1,
		customerName : "R K STEEL MANUFACTURING COMPANY PRIVATE LIMITED",
		customerCode : "INR 0015",
		customerCountryIdFk : 105,
		customerStatus : true,
    // custGlobalCompanyId: 2,
    // custCompanyCountryId: 1,
    // custCompanyBranchId :1,
		createdBy : 4,
		modifiedBy : 4,
		createdAt : new Date(),
		updatedAt : new Date(),
	},
	{
		id : 27,
		customerBranchId : 1,
		customerName : "J. V. CANDY COMPANY",
		customerCode : "INJ.0016",
		customerCountryIdFk : 105,
		customerStatus : true,
    // custGlobalCompanyId: 2,
    // custCompanyCountryId: 1,
    // custCompanyBranchId :1,
		createdBy : 4,
		modifiedBy : 4,
		createdAt : new Date(),
		updatedAt : new Date(),
	},
	{
		id : 28,
		customerBranchId : 1,
		customerName : "VASU CHEMICAL INDUSTRIES",
		customerCode : "INVA0017",
		customerCountryIdFk : 105,
		customerStatus : true,
    // custGlobalCompanyId: 2,
    // custCompanyCountryId: 1,
    // custCompanyBranchId :1,
		createdBy : 4,
		modifiedBy : 4,
		createdAt : new Date(),
		updatedAt : new Date(),
	},
	{
		id : 29,
		customerBranchId : 1,
		customerName : "MADRAS ENGINEERING INDUSTRIES PVT LTD",
		customerCode : "INMA0018",
		customerCountryIdFk : 105,
		customerStatus : true,
    // custGlobalCompanyId: 2,
    // custCompanyCountryId: 1,
    // custCompanyBranchId :1,
		createdBy : 4,
		modifiedBy : 4,
		createdAt : new Date(),
		updatedAt : new Date(),
	},
	{
		id : 30,
		customerBranchId : 1,
		customerName : "HABIB LEATHER MANUFACTURING COMPANY",
		customerCode : "INHA0019",
		customerCountryIdFk : 105,
		customerStatus : true,
    // custGlobalCompanyId: 2,
    // custCompanyCountryId: 1,
    // custCompanyBranchId :1,
		createdBy : 4,
		modifiedBy : 4,
		createdAt : new Date(),
		updatedAt : new Date(),
	},
	{
		id : 31,
		customerBranchId : 1,
		customerName : "HABIB LEATHER MANUFACTURING COMPANY",
		customerCode : "USHA0007",
		customerCountryIdFk : 233,
		customerStatus : true,
    // custGlobalCompanyId: 2,
    // custCompanyCountryId: 1,
    // custCompanyBranchId :1,
		createdBy : 4,
		modifiedBy : 4,
		createdAt : new Date(),
		updatedAt : new Date(),
	},
	{
		id : 32,
		customerBranchId : 1,
		customerName : "HP LOGISTICS",
		customerCode : "DKHP0002",
		customerCountryIdFk : 59,
		customerStatus : true,
    // custGlobalCompanyId: 2,
    // custCompanyCountryId: 1,
    // custCompanyBranchId :1,
		createdBy : 4,
		modifiedBy : 4,
		createdAt : new Date(),
		updatedAt : new Date(),
	},
	{
		id : 33,
		customerBranchId : 1,
		customerName : "BABU AND CO",
		customerCode : "INBA0020",
		customerCountryIdFk : 105,
		customerStatus : true,
    // custGlobalCompanyId: 2,
    // custCompanyCountryId: 1,
    // custCompanyBranchId :1,
		createdBy : 4,
		modifiedBy : 4,
		createdAt : new Date(),
		updatedAt : new Date(),
	}
    ]);
  },

  async down(queryInterface, Sequelize) {
    return queryInterface.bulkDelete("sc_customers", null, {});
  },
};
