"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    return queryInterface.bulkInsert("sc_incoterms", [
      {
        incoTermName : "EXW ",
        incoTermDescription : "Ex-Works",
        incoTermFreightTerm : "Collect",
        status : true,
        createdBy : 1,
        modifiedBy : 1,
        createdAt :new Date(),
        updatedAt :new Date(),
      },
      {
        incoTermName : "FCA",
        incoTermDescription : "Free Carrier",
        incoTermFreightTerm : "Collect",
        status : true,
        createdBy : 1,
        modifiedBy : 1,
        createdAt :new Date(),
        updatedAt :new Date(),
      },
      {
        incoTermName : "FAS",
        incoTermDescription : "Free Alongside Ship",
        incoTermFreightTerm : "Collect",
        status : true,
        createdBy : 1,
        modifiedBy : 1,
        createdAt :new Date(),
        updatedAt :new Date(),
      },
      {
        incoTermName : "FOB",
        incoTermDescription : "Free On Board",
        incoTermFreightTerm : "Collect",
        status : true,
        createdBy : 1,
        modifiedBy : 1,
        createdAt :new Date(),
        updatedAt :new Date(),
      },
      {
        incoTermName : "CFR",
        incoTermDescription : "Cost and Freight",
        incoTermFreightTerm : "Prepaid",
        status : true,
        createdBy : 1,
        modifiedBy : 1,
        createdAt :new Date(),
        updatedAt :new Date(),
      },
      {
        incoTermName : "CIF",
        incoTermDescription : "Cost, Insurance and Freight",
        incoTermFreightTerm : "Prepaid",
        status : true,
        createdBy : 1,
        modifiedBy : 1,
        createdAt :new Date(),
        updatedAt :new Date(),
      },
      {
        incoTermName : "CPT",
        incoTermDescription : "Carriage Paid To",
        incoTermFreightTerm : "Prepaid",
        status : true,
        createdBy : 1,
        modifiedBy : 1,
        createdAt :new Date(),
        updatedAt :new Date(),
      },
      {
        incoTermName : "CIP",
        incoTermDescription : "Carriage And Insurance Paid To",
        incoTermFreightTerm : "Prepaid",
        status : true,
        createdBy : 1,
        modifiedBy : 1,
        createdAt :new Date(),
        updatedAt :new Date(),
      },
      {
        incoTermName : "DPU",
        incoTermDescription : "Delivered At Place Unloaded ",
        incoTermFreightTerm : "Prepaid",
        status : true,
        createdBy : 1,
        modifiedBy : 1,
        createdAt :new Date(),
        updatedAt :new Date(),
      },
      {
        incoTermName : "DAP",
        incoTermDescription : "Delivered at Place  ",
        incoTermFreightTerm : "Prepaid",
        status : true,
        createdBy : 1,
        modifiedBy : 1,
        createdAt :new Date(),
        updatedAt :new Date(),
      },
      {
        incoTermName : "DDP",
        incoTermDescription : "Delivered Duty Paid",
        incoTermFreightTerm : "Prepaid",
        status : true,
        createdBy : 1,
        modifiedBy : 1,
        createdAt :new Date(),
        updatedAt :new Date(),
      },
      {
        incoTermName : "ALL",
        incoTermDescription : "ALL",
        incoTermFreightTerm : "ALL",
        status : true,
        createdBy : 1,
        modifiedBy : 1,
        createdAt :new Date(),
        updatedAt :new Date(),
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    return queryInterface.bulkDelete("sc_incoterms", null, {});
  },
};
