"use strict";

const { DATEONLY } = require("sequelize");

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    return queryInterface.bulkInsert("sc_sailing_schedules", [
      {
        POL: 7,
        POD: 96,
        linerName: 1,
        vesselName: 2,
        ETA: new Date(),
        ETD: new Date(),
        linerCutOff: new Date(),
        vgmCutOff: new Date(),
        portCutOff: new Date(),
        docsCutOff: new Date(),
        amsCutOff: new Date(),
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        POL: 7,
        POD: 2,
        linerName: 1,
        vesselName: 2,
        ETA: new Date(),
        ETD: new Date(),
        linerCutOff: new Date(),
        vgmCutOff: new Date(),
        portCutOff: new Date(),
        docsCutOff: new Date(),
        amsCutOff: new Date(),
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        POL: 6,
        POD: 1,
        linerName: 6,
        vesselName: 94,
        ETA: new Date(),
        ETD: new Date(),
        linerCutOff: new Date(),
        vgmCutOff: new Date(),
        portCutOff: new Date(),
        docsCutOff: new Date(),
        amsCutOff: new Date(),
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        POL: 1,
        POD: 1,
        linerName: 2,
        vesselName: 3,
        ETA: new Date(),
        ETD: new Date(),
        linerCutOff: new Date(),
        vgmCutOff: new Date(),
        portCutOff: new Date(),
        docsCutOff: new Date(),
        amsCutOff: new Date(),
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        POL: 5521,
        POD: 10263,
        linerName: 4,
        vesselName: 15,
        ETA: new Date(),
        ETD: new Date(),
        linerCutOff: new Date(),
        vgmCutOff: new Date(),
        portCutOff: new Date(),
        docsCutOff: new Date(),
        amsCutOff: new Date(),
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        POL: 1,
        POD: 6,
        linerName: 17,
        vesselName: 16,
        ETA: new Date(),
        ETD: new Date(),
        linerCutOff: new Date(),
        vgmCutOff: new Date(),
        portCutOff: new Date(),
        docsCutOff: new Date(),
        amsCutOff: new Date(),
        status: true,
        createdBy: 1,
        modifiedBy: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    return queryInterface.bulkDelete("sc_sailing_schedules", null, {});
  },
};
