"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    return queryInterface.bulkInsert("sc_employees", [
      {
        empBchName : "ABC LOGISTICS",
        empBchId : 1,
        empCode : null,
        empDeptId : null,
        empDesigId : 5,
        empDob : "1993-12-30",
        empEmail : "asadas@sdfdsdf",
        empFirstName : "Arun ",
        empGender : "Male",
        empIdKey : null,
        empLastName : "Kumar",
        empLogId : 1,
        empPhone : 7755331133,
        empSales : "YES",
        empStatus : "ACTIVE",
        createdBy : 1,
        modifiedBy : 1,
        employeeRole: 1,
        password: '',
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        empBchName : "ABC LOGISTICS",
        empBchId : 1,
        empCode : null,
        empDeptId : null,
        empDesigId : 13,
        empDob : "1976-09-30",
        empEmail : "sdvgh#@NKJDFD",
        empFirstName : "Lilly",
        empGender : "Female",
        empIdKey : null,
        empLastName : "S",
        empLogId : 1,
        empPhone : 8855223366,
        empSales : "NO",
        empStatus : "ACTIVE",
        createdBy : 1,
        modifiedBy : 1,
        createdAt : new Date(),
        employeeRole: 1,
        password: '',
        updatedAt : new Date()
      },
      {
        empBchName : "ABC LOGISTICS",
        empBchId : 1,
        empCode : null,
        empDeptId : null,
        empDesigId : 17,
        empDob : "2022-11-09",
        empEmail : "abdulhannanit.m@gmail.com",
        empFirstName : "Abdul",
        empGender : "Male",
        empIdKey : null,
        empLastName : "Hannan",
        empLogId : 1,
        empPhone : 9600986026,
        empSales : "YES",
        empStatus : "ACTIVE",
        createdBy : 1,
        modifiedBy : 1,
        employeeRole: 1,
        password: '',
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        empBchName : "ABC Logistics",
        empBchId : 1,
        empCode : null,
        empDeptId : null,
        empDesigId : 3,
        empDob : "1994-12-31",
        empEmail : "dsfs@asdasd",
        empFirstName : "Raj",
        empGender : "Male",
        empIdKey : null,
        empLastName : "Kumar",
        empLogId : 1,
        empPhone : 9955336622,
        empSales : "YES",
        empStatus : "DEACTIVE",
        createdBy : 1,
        modifiedBy : 1,
        employeeRole: 1,
        password: '',
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        empBchName : "ABC LOGISTICS",
        empBchId : 1,
        empCode : null,
        empDeptId : null,
        empDesigId : 5,
        empDob : "1999-12-29",
        empEmail : "awda@adsasd",
        empFirstName : "Abdul",
        empGender : "Female",
        empIdKey : null,
        empLastName : "Hannan",
        empLogId : 1,
        empPhone : 7755339955,
        empSales : "YES",
        empStatus : "ACTIVE",
        createdBy : 1,
        modifiedBy : 1,
        employeeRole: 1,
        password: '',
        createdAt : new Date(),
        updatedAt : new Date()
      },
      {
        empBchName : "ABC LOGISTICS",
        empBchId : 1,
        empCode : null,
        empDeptId : null,
        empDesigId : 5,
        empDob : "1999-12-29",
        empEmail : "awda@adsasd",
        empFirstName : "RISHIKESH",
        empGender : "Male",
        empIdKey : null,
        empLastName : "VENKATSAN",
        empLogId : 1,
        empPhone : 7755339955,
        empSales : "YES",
        empStatus : "ACTIVE",
        createdBy : 1,
        modifiedBy : 1,
        employeeRole: 1,
        password: '',
        createdAt : new Date(),
        updatedAt : new Date()
      }
    ]
    );
    
  },

  async down(queryInterface, Sequelize) {
    return queryInterface.bulkDelete("sc_employees", null, {});
  },
};
