"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    return queryInterface.bulkInsert(
      "sc_carriers",
      [
        {
          carrierCode: "AVCL",
          carrierName: "ADVANCE CONTAINER LINE",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "AIRTIGER",
          carrierName: "AIR TIGER EXPRESS ( ASIA) INC",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "APDD",
          carrierName: "APL SHIPPING LINE",
          carrierScac: "APLU",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "ARCL",
          carrierName: "ARC LINE",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "APCL",
          carrierName: "ASIA PACIFIC CONTAINER LINE",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "ASSJ",
          carrierName: "ASIAN SHIPPING. LTD.",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "ASKGOJO",
          carrierName: "ASK GOJO CONTAINER LINES",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "ACLU",
          carrierName: "ATLANTIC CONTAINER LINE",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "ATLINE",
          carrierName: "ATLAS LINE",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "ATLAS",
          carrierName: "ATLAS LOGISTICS PVT. LTD.",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "AALV",
          carrierName: "AUSTRAL ASIA LINE",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "ANNU",
          carrierName: "AUSTRALIAN NATIONAL LINE",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "BMC",
          carrierName: "B.M.C. LINE SHIPPING SVS (LLC)",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "NSAU",
          carrierName: "BAHRI LOGISTICS",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "BALAJI",
          carrierName: "BALAJI LOGISTICS",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "BSL",
          carrierName: "BALAJI SHIPPING LINES FZCO",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "BWAG",
          carrierName: "BARWIL AGENCIES INC",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "BYLM",
          carrierName: "BAY LINES",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "BENU",
          carrierName: "BEN LINE CONTAINERS LTD",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "BCL",
          carrierName: "BENGAL CONTAINER LINE",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "BGLM",
          carrierName: "BENGAL MARINE INC",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "CCNI",
          carrierName: "CCNI LINE",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "CSCL",
          carrierName: "CHINA SHIPPING CONTAINER LINE",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "CCLU",
          carrierName: "CHINATRANS INT\\L LTD",
          carrierScac: "CCLU",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "CITYOCEAN",
          carrierName: "CITY OCEAN INTL INC",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "CMDU",
          carrierName: "CMA -CGM",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "CNCL",
          carrierName: "CNC LINE",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "COLLYE",
          carrierName: "COLLYER SHIPPING",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "CHAU",
          carrierName: "COMBINED TRANSPORT GROUP",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "MMGU",
          carrierName: "CONCORDE CONTAINER LINE",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "CWE",
          carrierName: "CONTAINER WORLDWIDE EXPRESS",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "CONT",
          carrierName: "CONTI ANNAPURNA IS742R",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "CCLL",
          carrierName: "CONTINENTAL CONTAINER LINES LTD.",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "CCBC",
          carrierName: "COSCO (CHINA OCEAN SHIPPING COMPANY)",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "CRES",
          carrierName: "CRESCENT SHIPPING AGENCY",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "CST",
          carrierName: "CROSS STAR FREIGHT CARRIERS LLC",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "CAMN",
          carrierName: "CROWLEY LINER SERVICES",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "CSAV",
          carrierName: "CSAV GROUP AGENCIES (INDIA) PVT.LTD.",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "EPIR",
          carrierName: "EMIRATES SHIPPING LINE",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "EUMEX",
          carrierName: "EUMEX LINE SHENZHEN LIMITED",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "SZLU",
          carrierName: "EURASIA FREIGHT SERVICE INC",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "EVMC",
          carrierName: "EVER GREEN",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "EXP",
          carrierName: "EXPRESS ATHENS",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "FTGM",
          carrierName: "FAIR TRADE GMBH",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "PAT",
          carrierName: "FORBES PATVOLK",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "GECOT",
          carrierName: "GEMADEPT CORPORATION",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "GLOBE",
          carrierName: "GLOBELINK MARINE (CHINA) PTE LTD",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "GLDS",
          carrierName: "GOLD STAR LINE LTD",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "GOOD",
          carrierName: "GOODRICH CONTAINER LINES",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "HHTR",
          carrierName: "H H TRANSPORT  INC.",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "HMGS",
          carrierName: "HAMBURG SUD LINE",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "HJSC",
          carrierName: "HANJIN SHIPPING",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "HLCU",
          carrierName: "HAPAG LLOYD",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "11QU",
          carrierName: "HEUNG-A SHIPPING CO.  LTD.",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "HOEG",
          carrierName: "HOEGH AUTOLINERS",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "HUA",
          carrierName: "HUA CHANG HAI 3 HAO",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "HUB",
          carrierName: "HUB MARINE",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "HUGO",
          carrierName: "HUGO SCHULTE",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "HDMU",
          carrierName: "HYUNDAI MERCHANT MARINE",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "IALU",
          carrierName: "IAL CONTAINER LINES",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "IAM",
          carrierName: "INTERASIA MARITIME (M) SDN BHD",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "IRL",
          carrierName: "IRON LINES LTD",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "ISLA",
          carrierName: "ISLAMIC REPUBLIC OF IRAN SHIPPING",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "JKE",
          carrierName: "JAKARTA EXPRESS",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "JELEMSPS",
          carrierName: "JELEM SHIPPING SERVICES",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "JSA",
          carrierName: "JSA GLOBAL",
          carrierScac: "JSAG",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "KLNI",
          carrierName: "K LINES INC",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "KGL",
          carrierName: "KGL LOGISTICS EMIRATES ( ANCHORAGE ) LLC",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "KMTC",
          carrierName: "KOREA MARINE TRANSPORT CO LTD",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "LCLLINES",
          carrierName: "LCL LINES",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "LILLY",
          carrierName: "LILLY LINE",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "LMTL",
          carrierName: "LMT LINE",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "MAEU",
          carrierName: "MAERSK LINE",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "MAGU",
          carrierName: "MAGELLAN MARITIME SERVICES GMBH",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "MAINFR",
          carrierName: "MAINFREIGHT INC.",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "MYIP",
          carrierName: "MALAYSIAN INTERNATIONAL SHIPPING CO",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "MAN",
          carrierName: "MANCHESTER MAERSK",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "MAR",
          carrierName: "MARIANA EXPRESS LINES",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "MATSON",
          carrierName: "MATSON SHIPPING LINE",
          carrierScac: "MATS",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "MCL",
          carrierName: "MAXICON CONTAINER LINE",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "MCC",
          carrierName: "MCC TRANSPORT SINGAPORE PTE LTD",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "MSCU",
          carrierName: "MEDITERRANEAN SHIPPING COMPANY (MSC)",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "MED",
          carrierName: "MEDKON LINES",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "MESL",
          carrierName: "MEKONG SHIPPING LINE LTD.",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "CNSC",
          carrierName: "MERCHANT SHIPPING SERVICES",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "MESSI",
          carrierName: "MESSINA LINE",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "MDXP",
          carrierName: "MIDAS EXPRESS",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "MOLU",
          carrierName: "MITSUI O.S.K. LINES",
          carrierScac: "ONEY",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "MMTU",
          carrierName: "MULTIMODAL TRANSPORTATION CORP INC",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "NLLU",
          carrierName: "NIPPON LINER SYSTEMS",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "NORU",
          carrierName: "NORASIA LINE",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "NTLP",
          carrierName: "NTL NAGAI TRANS",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "NYKU",
          carrierName: "NYK LINE",
          carrierScac: "ONEY",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "OWLU",
          carrierName: "OCEAN WORLD LINES INC",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "ONEY",
          carrierName: "ONE LINE",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "OOLU",
          carrierName: "OOCL",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "OOCLBRIS",
          carrierName: "OOCL BRISBANE",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "OESC",
          carrierName: "ORIENT EXPRESS LINE",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "TTI",
          carrierName: "ORIENT STAR TRANSPORT INTERNATIONAL LTD.",
          carrierScac: "OSTI",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "ORS",
          carrierName: "ORIENTAL SHIPPING LLC",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "OTH",
          carrierName: "OTHER CARRIERS",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "OECL",
          carrierName: "OVERSEAS EXPRESS CONTAINER LINES",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "PCLW",
          carrierName: "PACC CONTAINER LINE PTE. LTD.",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "PCND",
          carrierName: "PACIFIC CONCORD INTERNATIONAL CORP.",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "EALS",
          carrierName: "PACIFIC EAGLE LINES PTE.LTD.",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "PAIM",
          carrierName: "PACIFIC INTERMODAL TRANSPORT INC",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "PCIF",
          carrierName: "PACIFIC SHIPPING LIMITED",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "PAL",
          carrierName: "PAN ASIA LINE",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "ANAU",
          carrierName: "ALLIANCE NAVIGATION LINE",
          carrierScac: "ANLU",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "ACS",
          carrierName: "ACS LINES",
          carrierScac: "NULL",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "PELSG",
          carrierName: "PENDULUM EXPRESS LINES PTE LTD",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "PSHC",
          carrierName: "PENINSULA SHIPPERS CONSOLIDATION",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "PCIU",
          carrierName: "PIL LINE",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "PIOU",
          carrierName: "PIONEER SHIPPING LTD",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "PORTEVER",
          carrierName: "PORTEVER SHIPPING LTD",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "QNTT",
          carrierName: "QATAR NAVIGATION (QNNTC)",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "QCSL",
          carrierName: "QC SHIPPING",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "RLI",
          carrierName: "RAVE LINE INTERNATIONAL PTE. LTD",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "RCLU",
          carrierName: "RCL LINES",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "REDWOD",
          carrierName: "REDWOOD MULTIMODAL.",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "RGEC",
          carrierName: "REGIONAL EXPRESS COMPANY",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "SAFM",
          carrierName: "SAFMARINE",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "S046",
          carrierName: "SAMUDERA SHIPPING LINE",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "SBBINT",
          carrierName: "SBB INTERNATIONAL SHIPPING LLC",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "SEA",
          carrierName: "SEA CONSORTIUM",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "SEACO",
          carrierName: "SEACO",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "SCSJ",
          carrierName: "SEACON SERVICES LTD",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "SEAM",
          carrierName: "SEALAND MAERSK",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "SWSL",
          carrierName: "SEAWAYS SHIPPING LINE",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "SCUU",
          carrierName: "SHIPPING CORPORATION (SCI)",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "SENI",
          carrierName: "SINOKOR LINE",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "SML",
          carrierName: "SM LINE",
          carrierScac: "SMLM",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "STAU",
          carrierName: "STAR SHIPPING A/S",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "STAL",
          carrierName: "STARLINE AGENCIES ASIA PTE LTD",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "SXPG",
          carrierName: "STX PAN OCEAN",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "SGL",
          carrierName: "SUDDATH GLOBAL LOGISTICS",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "SXLU",
          carrierName: "SUN XPRESS CONTAINER LINES",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "ANL",
          carrierName: "SUNSHIP AGENCIES",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "TSLIN",
          carrierName: "T.S. LINES",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "TEX",
          carrierName: "TEXTAINER",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "TIT",
          carrierName: "TITAN",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "TKML",
          carrierName: "TKM CONTAINER LINE",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "TBA",
          carrierName: "TO BE ADVISED",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "TLXU",
          carrierName: "TRANS ASIAN SHIPPING SERVICES",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "TCSH",
          carrierName: "TRANS COASTAL SERVICES",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "TTGO",
          carrierName: "TRANS CONTAINER",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "TRS",
          carrierName: "TRANS LINER",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "TRKU",
          carrierName: "TURKON",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "UASCJEBEL",
          carrierName: "UASC ",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "UVSL",
          carrierName: "UNIVERSAL SHIPPING LINES",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "USLB",
          carrierName: "US LINES",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "VEGA",
          carrierName: "VEGA ORIENT LINE",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "WLWH",
          carrierName: "WALLENIUS WILHELMSEN",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "WHLU",
          carrierName: "WAN HAI LINES",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "YMLU",
          carrierName: "YANG MING LINE",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "ZLNL",
          carrierName: "Z LINE",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "ZIM",
          carrierName: "ZIM CONTAINER SERVICE",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          carrierCode: "ZIMINT",
          carrierName: "ZIM INTEGRATED SHIPPING SERVICES LTD",
          carrierScac: "",
          carrierStatus: true,
          createdBy: 1,
          modifiedBy: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ]
    );
  },

  async down(queryInterface, Sequelize) {
    return queryInterface.bulkDelete("sc_carriers", null, {});
  },
};
